base:
  project: Linear
  random_state: 42
  target_col: Air temperature [K]

data_source:
  g_source: Data_given\ai4i2020.csv

load_data:
  raw_dataset_csv: data\raw\ai4i2020.csv

split_data:
  train_path: data\processed\train_at.csv
  test_path: data\processed\test_at.csv
  test_size: 0.15

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models

reports:
  params: report\params.json
  scores: report\scores.json